pipeline:
  build:
    image: node:8
    commands:
      - yarn install

  lint:
    image: node:8
    commands:
      - yarn run lesshint
      - yarn run lint

  test:
    image: node:8
    commands:
      - yarn run test

  build:
    image: node:8
    commands:
      - yarn run build

  publish-image-current:
    image: plugins/docker
    repo: mavimo/drone-ui
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_COMMIT:0:8}

  publish-image-next:
    image: plugins/docker
    repo: mavimo/drone-ui
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - next
