pipeline:
  build:
    image: node:8
    commands:
      - yarn install
      - yarn run lesshint
      - yarn run test
      - yarn run lint
      - yarn run build

  publish-image:
    image: plugins/docker
    repo: mavimo/drone-ui
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_COMMIT:0:8}

  publish-image:
    image: plugins/docker
    repo: mavimo/drone-ui
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - next
